XSnoed.resource_version:			3.5

XSnoed.title:					S.N.O. Event Display
XSnoed.geometry:				320x320+20+20
*background:					Grey
*fontList:					-*-helvetica-bold-r-normal--14-*,\
						-*-helvetica-medium-r-normal--12-*:SMALL,\
						-*-clean-medium-r-*-*-12-*:FIXED
*XmText.fontList:				-*-helvetica-bold-r-normal--14-*

!! Special XSnoed settings 

XSnoed.water_level:				900
XSnoed.light_speed:				22.45

XSnoed.cal_file:				cal_default.dat
XSnoed.oca_file:				oca_visual.bin
XSnoed.file_path:				/usr/local/ph:/usr/local/xsnoed:/usr/local/lib/xsnoed:/usr/share/xsnoed
XSnoed.snodb_server:				localhost
XSnoed.snoman_server:				localhost
XSnoed.help_url:				http://manhattan.sno.laurentian.ca/xsnoed/xsnoed.html
XSnoed.password:				xsnoed_expert
XSnoed.outfile1:				xsnoed_out1.zdab
XSnoed.outfile2:				xsnoed_out2.zdab
XSnoed.outfile3:				xsnoed_out3.zdab
XSnoed.outfile4:				xsnoed_out4.zdab

XSnoed.hist_font:				-*-helvetica-medium-r-normal--12-*
XSnoed.label_font:				-*-helvetica-medium-r-normal--12-*
XSnoed.label_big_font:				-*-helvetica-medium-r-normal--24-*
XSnoed.open_windows:				0
XSnoed.history_cut:				1
XSnoed.hex_id:					0
XSnoed.time_zone:				0
XSnoed.angle_rad:				0
XSnoed.hit_xyz:					0
XSnoed.hit_size:				1.0
XSnoed.ncd_size:				2.5
XSnoed.load_trigger_settings:			0

XSnoed.bkg_col:					Black
XSnoed.text_col:				White
XSnoed.hid_col:					Grey40
XSnoed.frame_col:				White
XSnoed.axes_col:				ForestGreen
XSnoed.curcon_col:				Red
XSnoed.rcon_col:				SpringGreen
XSnoed.grid_col:				Grey
XSnoed.sun_col:					Goldenrod1
XSnoed.water_col:				RoyalBlue
XSnoed.mc_neutrino_col:				Aquamarine
XSnoed.mc_electron_col:				Orange
XSnoed.mc_neutron_col:				Coral
XSnoed.mc_gamma_col:				IndianRed
XSnoed.mc_photon_col:				HotPink
XSnoed.mc_special_col:				Yellow
XSnoed.mc_other_col:				Chartreuse2

XSnoed.num_cols:				42
XSnoed.hist_bins:				80
XSnoed.ncd_bins:				80
XSnoed.scale_under:				SkyBlue1
XSnoed.scale_col0:				RoyalBlue1
XSnoed.scale_col1:				LimeGreen
XSnoed.scale_col2:				Yellow
XSnoed.scale_col3:				Orange
XSnoed.scale_col4:				Red
XSnoed.scale_over:				Pink1
XSnoed.discarded_col:				Grey30

XSnoed.ves_cols:				32
XSnoed.vdark_col:				Grey40
XSnoed.vlit_col:				Grey80

XSnoed.alt_bkg_col:				White
XSnoed.alt_text_col:				Black
XSnoed.alt_hid_col:				Grey35
XSnoed.alt_frame_col:				Black
XSnoed.alt_axes_col:				ForestGreen
XSnoed.alt_curcon_col:				Red
XSnoed.alt_rcon_col:				SpringGreen
XSnoed.alt_grid_col:				Grey35
XSnoed.alt_sun_col:				Goldenrod2
XSnoed.alt_water_col:				RoyalBlue3
XSnoed.alt_mc_neutrino_col:			Aquamarine
XSnoed.alt_mc_electron_col:			Orange
XSnoed.alt_mc_neutron_col:			Coral
XSnoed.alt_mc_gamma_col:			HotPink
XSnoed.alt_mc_photon_col:			IndianRed
XSnoed.alt_mc_special_col:			OrangeRed
XSnoed.alt_mc_other_col:			Chartreuse2

XSnoed.alt_scale_under:				SkyBlue3
XSnoed.alt_scale_col0:				RoyalBlue3
XSnoed.alt_scale_col1:				SeaGreen
XSnoed.alt_scale_col2:				Goldenrod3
XSnoed.alt_scale_col3:				Orange
XSnoed.alt_scale_col4:				Red
XSnoed.alt_scale_over:				Pink3
XSnoed.alt_discarded_col:			Grey80

XSnoed.alt_vdark_col:				Grey40
XSnoed.alt_vlit_col:				Grey80

XSnoed.tac_min:					1000
XSnoed.tac_max:					3000
XSnoed.qhs_min:					400
XSnoed.qhs_max:					800
XSnoed.qhl_min:					400
XSnoed.qhl_max:					800
XSnoed.qlx_min:					400
XSnoed.qlx_max:					800
XSnoed.qhl_qhs_min:				-400
XSnoed.qhl_qhs_max:				400
XSnoed.cmos_rates_min:				0
XSnoed.cmos_rates_max:				8000
XSnoed.delta_t_min:				-50
XSnoed.delta_t_max:				150
XSnoed.cal_tac_min:				-100
XSnoed.cal_tac_max:				300
XSnoed.cal_qhs_min:				-50
XSnoed.cal_qhs_max:				350
XSnoed.cal_qhl_min:				-50
XSnoed.cal_qhl_max:				350
XSnoed.cal_qlx_min:				-50
XSnoed.cal_qlx_max:				350
XSnoed.cal_qhl_qhs_min:				-200
XSnoed.cal_qhl_qhs_max:				200
XSnoed.cal_hits_min:				0
XSnoed.cal_hits_max:				2
XSnoed.extra_min:				-100
XSnoed.extra_max:				100
XSnoed.shaper_min:				0
XSnoed.shaper_max:				100
XSnoed.ncd_scope_xmin:				0
XSnoed.ncd_scope_xmax:				15000
XSnoed.ncd_scope_ymin:				-100
XSnoed.ncd_scope_ymax:				100

XSnoed.proj_min:				-1.0
XSnoed.proj_max:				1e10
XSnoed.proj_screen:				-1.2

XSnoed.tube_radius:				851.153


!! Background colors

*xsnoedForm*background:				PapayaWhip
*xsnoedRowCol*background:			PapayaWhip
*xsnoedAbout*background:			PapayaWhip
*xsnoedWarn*background:				PapayaWhip
*xsnoedFileBox*background:			Grey
*xsnoedScroll1*background:			Grey
*xsnoedScroll2*background:			Grey
*xsnoedScroll3*background:			Grey


!! Menubar settings

*xsnoedMenu*background:				PapayaWhip
*xsnoedMenu*XmPushButton.marginLeft:		10
*xsnoedMenu*XmPushButton.marginRight:		5
*xsnoedMenu*XmPushButton.marginTop:		0
*xsnoedMenu*XmPushButton.marginBottom:		0
*xsnoedMenu*XmToggleButton.marginRight:		5
*xsnoedMenu*XmToggleButton.marginTop:		0
*xsnoedMenu*XmToggleButton.marginBottom:	0


!! Monte Carlo window fonts
*mcTitle*fontList:				-*-clean-bold-r-*-*-12-*
*mcTrack*fontList:				-*-clean-medium-r-*-*-12-*

